import'./image-fix.mjs';import'./sample-data.mjs';import{clubs,players}from'./data.mjs';import{esc,freshProfile,loadProfile,saveProfile,levelOf}from'./test.js';
const $=s=>document.querySelector(s),app=$('#app');let profile=loadProfile();
function sync(){if(!profile)return;$('#profileName').textContent=profile.username;$('#profileMeta').textContent=`${profile.rating}P · L${levelOf(profile)}`}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1800)}
function hydrate(root=document){if(window.EGImages?.hydrate)return window.EGImages.hydrate(root)}
function pimg(p){return`<img data-wiki="${esc(p.wikiTitle)}" alt="${esc(p.name)}">`}
function home(){app.innerHTML=`<section class="hero"><div class="hero-main"><div class="eyebrow">FUTBOL BİLGİSİ × STRATEJİ</div><h1>ELEVEN<br><span>GRID</span></h1><p>İki kulübün ortak futbolcusunu bul, kareyi ele geçir ve rakibinden önce üçlü bağlantıyı tamamla.</p><div class="actions"><button id="quick" class="primary">Hızlı Maç</button><button id="daily" class="secondary">Günün Gridi</button></div></div><aside class="panel"><h3>${esc(profile.username)}</h3><div class="statline"><span>Rating</span><b>${profile.rating}</b></div><div class="statline"><span>Seviye</span><b>L${levelOf(profile)}</b></div><div class="statline"><span>Galibiyet</span><b>${profile.wins}</b></div><div class="statline"><span>Maç</span><b>${profile.wins+profile.draws+profile.losses}</b></div></aside></section><div class="section-head"><h2>Oyun Modları</h2></div><section class="modes"><button class="mode" id="modeQuick"><span class="badge">1V1 · AI</span><b>Hızlı Maç</b><small>Gerçek kulüp kesişimleriyle çalışan maç.</small></button><button class="mode" id="modeDaily"><span class="badge">GÜNLÜK</span><b>Günün Gridi</b><small>Her gün sabitlenen tek oyunculu grid.</small></button><button class="mode" id="openDb"><span class="badge">VERİTABANI</span><b>Kariyer Arşivi</b><small>Aktif futbolcuları ve kulüp bağlantılarını incele.</small></button></section>`;$('#openDb').onclick=()=>nav('players');['#quick','#modeQuick'].forEach(s=>$(s).onclick=()=>window.startElevenGame?.('quick'));['#daily','#modeDaily'].forEach(s=>$(s).onclick=()=>window.startElevenGame?.('daily'))}
function playerView(){app.innerHTML=`<div class="section-head"><h2>Futbolcu Veritabanı</h2><p class="muted">${players.length} gerçek kariyer kaydı</p></div><div class="panel"><input id="dbSearch" class="search" placeholder="Futbolcu ara..."><div id="pcards" class="cards"></div></div>`;const draw=q=>{q=q.toLocaleLowerCase('tr-TR');$('#pcards').innerHTML=players.filter(p=>p.name.toLocaleLowerCase('tr-TR').includes(q)).map(p=>`<article class="card"><div class="photo">${pimg(p)}</div><div class="info"><b>${esc(p.name)}</b><small>${esc(p.country)} · ${p.clubs.length} kulüp</small></div></article>`).join('');hydrate($('#pcards'))};draw('');$('#dbSearch').oninput=e=>draw(e.target.value)}
function clubView(){app.innerHTML=`<div class="section-head"><h2>Kulüpler</h2><p class="muted">Grid motorunda aktif ${clubs.length} gerçek kulüp</p></div><div class="cards">${clubs.map(c=>`<article class="card club"><div class="photo"><img data-wiki="${esc(c.wikiTitle)}" alt="${esc(c.name)}"></div><div class="info"><b>${esc(c.name)}</b><small>${esc(c.country)}</small></div></article>`).join('')}</div>`;hydrate(app)}
function statView(){const total=profile.wins+profile.draws+profile.losses,wr=total?Math.round(profile.wins/total*100):0;app.innerHTML=`<div class="section-head"><h2>İstatistik</h2></div><section class="hero"><div class="panel"><div class="statline"><span>Rating</span><b>${profile.rating}</b></div><div class="statline"><span>Seviye</span><b>L${levelOf(profile)}</b></div><div class="statline"><span>Galibiyet oranı</span><b>%${wr}</b></div><div class="statline"><span>G/B/M</span><b>${profile.wins}/${profile.draws}/${profile.losses}</b></div></div><div class="panel"><h3>Son Maçlar</h3>${profile.matches.length?`<table class="table">${profile.matches.slice(0,10).map(m=>`<tr><td>${m.result==='win'?'Galibiyet':m.result==='loss'?'Mağlubiyet':'Berabere'}<small class="muted"> · ${esc(m.opponent)}</small></td><td>${m.delta>0?'+':''}${m.delta}P</td></tr>`).join('')}</table>`:'<p class="muted">Henüz maç yok.</p>'}</div></section>`}
function nav(v='home'){window.scrollTo(0,0);document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===v));v==='players'?playerView():v==='clubs'?clubView():v==='stats'?statView():home()}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#profileButton').onclick=()=>{$('#profileUsername').value=profile.username;$('#profileModal').classList.remove('hidden')};$('#profileClose').onclick=()=>$('#profileModal').classList.add('hidden');$('#profileForm').onsubmit=e=>{e.preventDefault();const n=$('#profileUsername').value.trim();if(n.length>=3){profile.username=n.slice(0,18);saveProfile(profile);sync();$('#profileModal').classList.add('hidden');nav('home')}};$('#resetProfile').onclick=()=>{localStorage.removeItem('eleven_grid_profile_v1');location.reload()};$('#usernameForm').onsubmit=e=>{e.preventDefault();const n=$('#usernameInput').value.trim();if(n.length>=3){profile=freshProfile(n.slice(0,18));saveProfile(profile);$('#usernameModal').classList.add('hidden');sync();nav('home')}};if(!profile){profile=freshProfile('Oyuncu');$('#usernameModal').classList.remove('hidden')}sync();window.EG={get profile(){return profile},save(){saveProfile(profile);sync()},sync,toast,hydrate,pimg,nav};nav('home');
export{profile,saveProfile,sync,toast,hydrate,pimg,nav};
