const queue=[];let active=0;const LIMIT=3,seen=new WeakSet();
function initials(label=''){return label.trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>Array.from(x)[0]||'').join('').toLocaleUpperCase('tr-TR')||'XI'}
function fallback(label,club=false){const bg=club?'#111c2c':'#17253a',fg=club?'#f3c85a':'#dbe6f4',r=club?20:100;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="220" height="220" viewBox="0 0 220 220"><rect width="220" height="220" rx="${r}" fill="${bg}"/><text x="110" y="126" text-anchor="middle" fill="${fg}" font-family="Arial" font-size="52" font-weight="800">${initials(label)}</text></svg>`;return`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
function pump(){while(active<LIMIT&&queue.length){const j=queue.shift();active++;Promise.resolve().then(j.task).then(j.resolve,j.resolve).finally(()=>{active--;pump()})}}
function queued(task){return new Promise(resolve=>{queue.push({task,resolve});pump()})}
async function searchImage(title){if(!title)return'';const c=new AbortController(),t=setTimeout(()=>c.abort(),5500);try{const q=new URLSearchParams({action:'query',generator:'search',gsrsearch:title,gsrlimit:'1',prop:'pageimages',piprop:'thumbnail',pithumbsize:'360',format:'json',origin:'*'});const r=await fetch(`https://en.wikipedia.org/w/api.php?${q}`,{signal:c.signal});if(!r.ok)return'';const d=await r.json(),pages=Object.values(d.query?.pages||{});return pages.find(p=>p?.thumbnail?.source)?.thumbnail?.source||''}catch{return''}finally{clearTimeout(t)}}
function repair(img){if(seen.has(img))return;seen.add(img);const club=img.closest('.club,.club-head')!=null,fb=fallback(img.alt||img.dataset.wiki||'XI',club);img.dataset.safeFallback=fb;if(!img.getAttribute('src'))img.src=fb;img.addEventListener('error',()=>{img.src=fb},{once:true});setTimeout(()=>{if(img.src.startsWith('data:image/svg'))queued(()=>searchImage(img.dataset.wiki)).then(url=>{if(url)img.src=url})},900)}
function scan(root=document){root.querySelectorAll?.('img[data-wiki]').forEach(repair)}
new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(n=>{if(n.nodeType===1){if(n.matches?.('img[data-wiki]'))repair(n);scan(n)}}))).observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener('DOMContentLoaded',()=>scan());setTimeout(()=>scan(),1200);
