import{clubById,players,boards,playerById}from'./data.mjs';import{eligiblePlayers,validPlayer,winner,isDraw,seededIndex}from'./engine.mjs';import{recordMatch,esc}from'./test.js';
const $=s=>document.querySelector(s),bots=['GridBot','Scout XI','Tempo AI','CornerLab'];let g,pick;
const head=id=>{const c=clubById[id];return`<div class="club-head"><img data-wiki="${esc(c.wikiTitle)}"><b>${esc(c.name)}</b></div>`};
function render(){const E=window.EG,b=g.board;let cells='';for(let r=0;r<3;r++){cells+=head(b.rows[r]);for(let c=0;c<3;c++){const i=r*3+c,v=g.cells[i];cells+=v?`<button class="cell filled ${v.owner}">${E.pimg(playerById[v.playerId])}<span>${esc(playerById[v.playerId].name)}</span></button>`:`<button class="cell" data-i="${i}"><i class="plus">+</i></button>`}}const top=g.mode==='quick'?`<div class="versus"><b>${esc(E.profile.username)} · ${E.profile.rating}P</b><b>VS</b><b>${g.bot} · AI</b></div>`:`<div class="versus"><b>Günün Gridi</b><b>${g.cells.filter(Boolean).length}/9</b></div>`;$('#app').innerHTML=`<div class="game-wrap">${top}<div class="turn">${g.done?'Oyun tamamlandı':g.mode==='daily'?'Tüm 9 kareyi doldur':g.turn==='human'?'Sıra sende':'AI düşünüyor...'}</div><div class="board"><div class="corner"><span class="brand-mark">XI</span></div>${b.cols.map(head).join('')}${cells}</div><div class="actions"><button class="secondary" id="gh">Ana Sayfa</button><button class="secondary" id="gn">Yeni Grid</button></div></div>`;E.hydrate($('#app'));$('#gh').onclick=()=>E.nav('home');$('#gn').onclick=()=>start(g.mode);$('#app').querySelectorAll('[data-i]').forEach(x=>x.onclick=()=>open(Number(x.dataset.i)))}
function start(mode='quick'){const day=new Date().toISOString().slice(0,10),bi=mode==='daily'?seededIndex(day,boards.length):Math.floor(Math.random()*boards.length);g={mode,board:boards[bi],cells:Array(9).fill(null),used:new Set(),turn:'human',done:false,bot:bots[Math.floor(Math.random()*bots.length)]};render()}
function open(i){if(g.done||g.turn!=='human')return;pick=i;const r=g.board.rows[Math.floor(i/3)],c=g.board.cols[i%3];$('#pickerTitle').textContent=clubById[r].name+' × '+clubById[c].name;$('#pickerModal').classList.remove('hidden');$('#playerSearch').value='';list('')}
function list(q){const E=window.EG,n=q.toLocaleLowerCase('tr-TR');$('#playerChoices').innerHTML=players.filter(p=>p.name.toLocaleLowerCase('tr-TR').includes(n)).slice(0,20).map(p=>`<button class="choice" data-p="${p.id}">${E.pimg(p)}<div><b>${esc(p.name)}</b><small>${esc(p.country)} · ${esc(p.position)}</small></div></button>`).join('');E.hydrate($('#playerChoices'));$('#playerChoices').querySelectorAll('[data-p]').forEach(x=>x.onclick=()=>choose(x.dataset.p))}
function choose(id){const E=window.EG,p=playerById[id],r=g.board.rows[Math.floor(pick/3)],c=g.board.cols[pick%3];$('#pickerModal').classList.add('hidden');if(!validPlayer(p,r,c,g.used)){E.toast(g.used.has(id)?'Bu futbolcu zaten kullanıldı.':'Bu futbolcu iki kulüpte de oynamadı.');if(g.mode==='quick'){g.turn='ai';render();setTimeout(ai,500)}return}g.cells[pick]={owner:'human',playerId:id};g.used.add(id);if(g.mode==='daily'){if(g.cells.every(Boolean)){g.done=true;E.toast('Günün gridi tamamlandı!')}render();return}if(check())return;g.turn='ai';render();setTimeout(ai,500)}
function ai(){const open=[];for(let i=0;i<9;i++){if(g.cells[i])continue;const r=g.board.rows[Math.floor(i/3)],c=g.board.cols[i%3],o=eligiblePlayers(players,r,c,g.used);if(o.length)open.push({i,o})}if(!open.length)return finish('draw');let m;for(const owner of['ai','human']){m=open.find(x=>{const cp=g.cells.slice();cp[x.i]={owner,playerId:x.o[0].id};return winner(cp)?.owner===owner});if(m)break}m??=open[Math.floor(Math.random()*open.length)];const p=m.o[Math.floor(Math.random()*m.o.length)];g.cells[m.i]={owner:'ai',playerId:p.id};g.used.add(p.id);if(!check()){g.turn='human';render()}}
function check(){const w=winner(g.cells);if(w){finish(w.owner==='human'?'win':'loss');return true}if(isDraw(g.cells)){finish('draw');return true}return false}
function finish(result){g.done=true;g.turn='done';render();if(g.mode==='quick'){const E=window.EG,d=recordMatch(E.profile,result,g.bot,g.board.name);E.sync();E.toast(`${result==='win'?'Galibiyet':result==='loss'?'Mağlubiyet':'Berabere'} · ${d>0?'+':''}${d} P`)}}
$('#pickerClose').onclick=()=>$('#pickerModal').classList.add('hidden');$('#playerSearch').oninput=e=>list(e.target.value);window.startElevenGame=start;
