import{clubById,players,boards,playerById}from'./data.mjs';import{eligiblePlayers,validPlayer,winner,isDraw,seededIndex}from'./engine.mjs';import{recordMatch,esc}from'./test.js';
let g;const $=s=>document.querySelector(s),bots=['GridBot','Scout XI','Tempo AI','CornerLab'];
const head=id=>{const c=clubById[id];return`<div class="club-head"><img data-wiki="${esc(c.wikiTitle)}" alt="${esc(c.name)}"><b>${esc(c.name)}</b></div>`};
function draw(){const E=window.EG,b=g.board;let x=`<div class="game-wrap">${g.mode==='quick'?`<div class="versus"><div class="who"><div class="avatar">${esc(E.profile.username.slice(0,2).toUpperCase())}</div><div><b>${esc(E.profile.username)}</b><small>${E.profile.rating} P</small></div></div><b>VS</b><div class="who"><div><b>${g.bot}</b><small>AI rakip</small></div><div class="avatar">AI</div></div></div>`:`<div class="versus"><b>Günün Gridi</b><b>${g.cells.filter(Boolean).length}/9</b></div>`}<div class="turn">${g.turn==='done'?'Oyun tamamlandı':g.mode==='daily'?'Bir kare seç':g.turn==='human'?'Sıra sende':'AI oynuyor...'}</div><div class="board"><div class="corner"><span class="brand-mark">XI</span></div>${b.cols.map(head).join('')}`;for(let r=0;r<3;r++){x+=head(b.rows[r]);for(let c=0;c<3;c++){const i=r*3+c,v=g.cells[i];x+=v?`<button class="cell filled ${v.owner}" data-i="${i}">${E.pimg(playerById[v.playerId])}<span>${esc(playerById[v.playerId].name)}</span></button>`:`<button class="cell" data-i="${i}"><i class="plus">+</i></button>`}}x+=`</div><div class="actions"><button class="secondary" id="gHome">Ana Sayfa</button><button class="secondary" id="gNew">Yeni Grid</button></div></div>`;$('#app').innerHTML=x;E.hydrate($('#app'));$('#gHome').onclick=()=>E.nav('home');$('#gNew').onclick=()=>start(g.mode);$('#app').querySelectorAll('.cell:not(.filled)').forEach(b=>b.onclick=()=>pick(Number(b.dataset.i)))}
function pick(i){if(g.turn!=='human')return;const name=prompt('Bu iki kulüpte de oynamış futbolcu adı:');if(!name)return;const p=players.find(x=>x.name.toLocaleLowerCase('tr-TR')===name.trim().toLocaleLowerCase('tr-TR')),r=g.board.rows[Math.floor(i/3)],c=g.board.cols[i%3];if(!validPlayer(p,r,c,g.used)){window.EG.toast('Yanlış veya daha önce kullanılmış futbolcu.');if(g.mode==='quick'){g.turn='ai';draw();setTimeout(ai,450)}return}g.cells[i]={owner:'human',playerId:p.id};g.used.add(p.id);if(end())return;if(g.mode==='daily'){draw();if(g.cells.every(Boolean)){g.turn='done';draw();window.EG.toast('Günün gridi tamamlandı!')}return}g.turn='ai';draw();setTimeout(ai,450)}
function ai(){const a=[];for(let i=0;i<9;i++){if(g.cells[i])continue;const r=g.board.rows[Math.floor(i/3)],c=g.board.cols[i%3],o=eligiblePlayers(players,r,c,g.used);if(o.length)a.push({i,o})}if(!a.length){finish('draw');return}const m=a[Math.floor(Math.random()*a.length)],p=m.o[Math.floor(Math.random()*m.o.length)];g.cells[m.i]={owner:'ai',playerId:p.id};g.used.add(p.id);if(!end()){g.turn='human';draw()}}
function end(){const w=winner(g.cells);if(w){finish(w.owner==='human'?'win':'loss');return true}if(isDraw(g.cells)){finish('draw');return true}return false}
function finish(result){g.turn='done';draw();if(g.mode==='quick'){const E=window.EG,d=recordMatch(E.profile,result,g.bot,g.board.name);E.sync();E.toast((result==='win'?'Galibiyet!':result==='loss'?'Mağlubiyet':'Berabere')+' · '+(d>0?'+':'')+d+' P')}}
function start(mode='quick'){const d=new Date().toISOString().slice(0,10),i=mode==='daily'?seededIndex(d,boards.length):Math.floor(Math.random()*boards.length);g={mode,board:boards[i],cells:Array(9).fill(null),used:new Set(),turn:'human',bot:bots[Math.floor(Math.random()*bots.length)]};draw()}
window.startElevenGame=start;
