import test from'node:test';import assert from'node:assert/strict';import{clubs,players,boards}from'../js/data.mjs';import{boardIsPlayable,eligiblePlayers,validPlayer,winner,seededIndex}from'../js/engine.mjs';
test('all boards are playable',()=>{for(const b of boards)assert.equal(boardIsPlayable(b,players),true,b.name)});
test('Real Madrid x Juventus has answers',()=>assert.ok(eligiblePlayers(players,'real-madrid','juventus').length>=3));
test('winner detects row column and diagonal',()=>{assert.equal(winner([{owner:'human'},{owner:'human'},{owner:'human'},null,null,null,null,null,null]).owner,'human');assert.equal(winner([{owner:'ai'},null,null,{owner:'ai'},null,null,{owner:'ai'},null,null]).owner,'ai');assert.equal(winner([{owner:'human'},null,null,null,{owner:'human'},null,null,null,{owner:'human'}]).owner,'human')});
test('all boards have nine distinct usable players',()=>{for(const b of boards){const o=b.rows.flatMap(r=>b.cols.map(c=>eligiblePlayers(players,r,c).map(p=>p.id))),m=new Map();function add(cell,seen){for(const id of o[cell]){if(seen.has(id))continue;seen.add(id);if(!m.has(id)||add(m.get(id),seen)){m.set(id,cell);return true}}return false}let n=0;for(let i=0;i<9;i++)if(add(i,new Set()))n++;assert.equal(n,9,b.name)}});
test('club and player ids are unique and references are valid',()=>{const clubIds=new Set(clubs.map(c=>c.id)),playerIds=new Set(players.map(p=>p.id));assert.equal(clubIds.size,clubs.length);assert.equal(playerIds.size,players.length);for(const p of players){assert.ok(p.name&&p.wikiTitle,p.id);for(const c of p.clubs)assert.ok(clubIds.has(c),`${p.id}: ${c}`)}});
test('board definitions only use known, non-duplicated clubs',()=>{const ids=new Set(clubs.map(c=>c.id));for(const b of boards){assert.equal(new Set(b.rows).size,3,b.name);assert.equal(new Set(b.cols).size,3,b.name);for(const c of [...b.rows,...b.cols])assert.ok(ids.has(c),`${b.name}: ${c}`);for(const c of b.rows)assert.ok(!b.cols.includes(c),`${b.name}: ${c} repeated across axes`)}});
test('used players cannot be submitted again',()=>{const p=eligiblePlayers(players,'real-madrid','juventus')[0];assert.ok(p);assert.equal(validPlayer(p,'real-madrid','juventus',new Set()),true);assert.equal(validPlayer(p,'real-madrid','juventus',new Set([p.id])),false)});
test('daily seed is deterministic and in range',()=>{for(const seed of['2026-08-13','2026-08-14','abc']){const a=seededIndex(seed,boards.length);assert.equal(a,seededIndex(seed,boards.length));assert.ok(a>=0&&a<boards.length)}});
